# Generated by Django 4.2.3 on 2023-07-26 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_add_slug_to_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='zip',
            field=models.CharField(default='60194', max_length=5),
            preserve_default=False,
        ),
    ]
